[project]
name = "code-presenter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygments>=2.19.2",
    "tree-sitter>=0.24.0",
    "tree-sitter-python>=0.23.6",
]
